name: Build and Deploy Lambda Image to ECR

on:
  push:
    branches:
      - main
    paths:
        - 'src/file_converter_ecr_image/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2        
      ECR_REPOSITORY: libreoffice-converter
      IMAGE_TAG: latest
      CDK_STACK_NAME: CW357221ParametrosDevOps-LambdaEcrS3TriggerStack

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker build \
            -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            -f src/file_converter_ecr_image/Dockerfile \
            src/file_converter_ecr_image
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Install CDK and dependencies
        run: |
          pip install -r infra/requirements.txt
          npm install -g aws-cdk

      - name: Synthesize CDK
        working-directory: infra
        run: cdk synth ${{ env.CDK_STACK_NAME }}       

      - name: Deploy CDK Stack
        working-directory: infra
        run: |
            cdk deploy ${{ env.CDK_STACK_NAME }} --require-approval never
